version: '3.9'

services:
  app:
    container_name: natours-backend
    build: .
    restart: always
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DATABASE=mongodb://mongo:27017/natours
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
    networks:
      - natours-network
    volumes:
      - ./logs:/app/logs
      - ./public/img:/app/public/img

  mongo:
    image: mongo:7.0
    container_name: natours-mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=natours
    volumes:
      - mongo_data:/data/db
    restart: always

networks:
  natours-network:

volumes:
  mongo_data:
